env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - amd64
      - arm64
      # - arm
      # - "386"
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=go-zoox
